### ISSUE TITLE
Explicit type annotation for unit

### ISSUE THREAD

**Issue by rickyvetter** [rescript-lang/syntax#383] opened 2021-04-12 17:08 UTC
[`let foo = ((): unit)`](https://rescript-lang.org/try?code=DYUwLgBAZg9jEF4IApkEoBcECuA7AlmGkA)

Gets an error:
The code is not valid ReScript syntax.
[E] Line 1, column 19:
Did you forget a `=>` here?

**Comment by bobzhang** [comment] 2021-04-17 01:49
I am thinking of instead of fix it. How about giving the unit expression a new syntax instead of overloading `()`, for example `Void`.
Why I am proposing this is that `()` is already heavily loaded in tuple, call, and a bunch of other places, unit expression is rarely used, so maybe we can give it a new name instead

**Comment by IwanKaramazow** [comment] 2021-04-17 12:50
It would still be good to also fix the underlying problem. 
Interesting note, this is also a bug in TypeScript:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/10634678/115113647-98565f80-9f8b-11eb-8fd5-d73acb97f78f.png">

It's a bit unfortunate that JS added the arrow function to their language. From a parser perspective the implementation needs to have a lookahead. Anyway, looking into the underlying issue.

**Comment by a-c-sreedhar-reddy** [comment] 2021-04-17 20:22
Does `()` in typescript mean void?

If not then the above error message in TS is not a bug.

**Comment by phenax** [comment] 2021-04-18 06:07
@IwanKaramazow, `let x = ()` is not valid typescript either so it isn't related.

Also, this seems to work fine -
```rescript
let foo = (():> unit)
```

I'm guessing [this](https://github.com/rescript-lang/syntax/blob/1680ae5d0e5546f5a150e028a148aeee257bcd20/src/res_core.ml#L2292) is the culprit.

**Comment by IwanKaramazow** [comment] 2021-04-18 09:59
@phenax uf yes, forgot that `()` doesn't exist in typescript. That syntax error makes total sense.

As @a-c-sreedhar-reddy diagnosed correctly in https://github.com/rescript-lang/syntax/pull/389, the parser thinks it's an arrow function.

@bobzhang the `()` is indeed super overloaded, good point. Maybe we could start thinking about an alternative syntax in the long term?

**Comment by IwanKaramazow** [comment] 2021-04-23 05:42
Fixed in https://github.com/rescript-lang/syntax/pull/389

**Closed by IwanKaramazow** 2021-04-23 05:42 UTC
