### ISSUE TITLE
Formatter removing record field punning?

### ISSUE THREAD

**Issue by illusionalsagacity** [rescript-lang/syntax#252] opened 2021-01-29 14:28 UTC
Is this intended behavior? I seem to remember `refmt` automatically using punning

https://rescript-lang.org/try?code=PTAEAUBsFMEMGdqgHYHsAu0BcAoEoBaIvMAFQAskpYBPAcwCdUBXZAE1AEt5R51PIkULFAB3VAwDWXZKAAOTRtHjwSoAErQAygGMGnOelBhUkDpoSpZ8GsnSwAHr3Isz82A0SgAVsz5qAM05kJAAKOlRQdEj0SlAAIi1odH5kOnh49xChAIko1Do6SGC6Xlt7BwBKADoSNQAxaGgchib8+UhaYSZWDlh2UB1UAFs5ASR4Eeg1TV19Q0HUNmgAQhwcdBo5JFzIgF5QAG9YLF50fTSAGlAAI1O+C7oAX3WYIxED+IDYSWh4nDet1An2iv2Q-wByUGwKOsGuNxeQA

```res
type example = {a: string, b: string}
let a = "fake"
let b = "token"
let c = {a, b}
```

gets formatted to:

```res
type example = {a: string, b: string}
let a = "fake"
let b = "token"
let c = {a: a, b: b}
```

**Comment by pckilgore** [comment] 2021-01-29 15:19
You might be interested in #64 / if not a dupe of #47 I'd add more info!

**Comment by illusionalsagacity** [comment] 2021-01-29 15:35
> You might be interested in #64 / if not a dupe of #47 I'd add more info!

Thanks! It does appear to be a dupe of #47

**Comment by illusionalsagacity** [comment] 2021-01-29 16:38
Hm, on second look no it's not, this is for initializing the record in a let assignment or return value, not a type declaration

**Comment by IwanKaramazow** [comment] 2021-01-30 09:26
Hmm, this is indeed a good point. I've probably missed this in the whole ReScript syntax rewrite. Thanks for pointing this out. Looking into this.

**Comment by cknitt** [comment] 2021-04-29 10:19
Formatting the punning away makes the code more verbose/harder to read.

My understanding, too, is that punning should only go away for type declarations, not for record initialization, see https://github.com/rescript-lang/syntax/pull/64#issuecomment-666879913.

**Comment by ryyppy** [comment] 2022-05-02 16:12
Fixed

**Closed by ryyppy** 2022-05-02 16:12 UTC
