### ISSUE TITLE
Formatter is trying to add a star to a zero-argument functor type

### ISSUE THREAD

**Issue by Shuenhoy** [rescript-lang/syntax#475] opened 2022-01-15 05:05 UTC
```rescript
module type B = () => {

}
```
would be formatted into 
```rescript
module type B = (*) => {

}
```
, causing compile error.

**Comment by amiralies** [comment] 2022-01-20 21:15
probably duplicate of #467

**Comment by ryyppy** [comment] 2022-03-23 07:17
fixed in master

**Closed** 2022-03-23 07:18 UTC
