### ISSUE TITLE
Incorrect js code generated moving from Reason to Rescript

### ISSUE THREAD

**Issue by BlueHotDog** [rescript-lang/syntax#399] opened 2021-04-30 20:35 UTC
We had this ReasonML code:
```
type t;
[@bs.new] external make: unit => t = "DOMParser";
[@bs.send.pipe: t]
external parseHtmlFromString: (string, [@bs.as "text/html"] _) => Dom.htmlDocument = "parseFromString";
```
Which, generated code just as expected on the call-site.

We transpiled that to Rescript. and now we're getting a weird 
```
import * as Caml_external_polyfill from "bs-platform/lib/es6/caml_external_polyfill.js";
 Caml_external_polyfill.resolve("parseFromString")(content, new DOMParser());
 ```
 on the call site. which, result in a runtime exception with some weird error saying this function isn't pollyfilled yet. 
My questions are:
Where is this magic coming from?
When was this magic introduced? 
 
 This caused a runtime exception in production and was completely unexpected and impossible for us to even know that it'll happen.

**Comment by cristianoc** [comment] 2021-05-01 02:19
Have you checked the difference in generated code after upgrade? That's the recommended way to proceed, which has been used by people successfully. The difference should be very nearly zero.

**Comment by IwanKaramazow** [comment] 2021-05-01 05:05
Hey @BlueHotDog, can you show me the code that is calling this external and results in the runtime problem?

I just converted your external Reason snippet to ReScript and compared the two. Both ASTs are the same, so I'm guessing that the problem is coming from the call site.

**Comment by BlueHotDog** [comment] 2021-05-01 09:03
@cristianoc having to manually check each file we transform would result in so much manual, careful labor since we dont even commit the JS files to git so i dont see how this is a solution - we're running rescript on thousands of files and tens of projects in a monorepo setup, doing this for evey file migration means we'll not move to rescript anytime soon which puts us between a rock and a hard place - Can't upgrade, can't trust an robust upgrade process.

**Comment by BlueHotDog** [comment] 2021-05-01 09:04
> Hey @BlueHotDog, can you show me the code that is calling this external and results in the runtime problem?
> 
> I just converted your external Reason snippet to ReScript and compared the two. Both ASTs are the same, so I'm guessing that the problem is coming from the call site.

Just tried it on the playground, the result is the same as i reported:
https://rescript-lang.org/try?code=C4TwDgpgBMBQACA7CB3KEAewICdEEMAbKAW3wGsIAuKAV0QEtgoBeAPhlagCIARAeQCyABXw4Azrm4JJiACYA6MA0gAKGsACUsTNjxEoYMZIASwEoQBiOAPYkAysBwNEAcxqrxTl64A0UeHxxVW5sLAB6AAtzQm5NKAB9ePYoXjsFaIs0gGNaEghEZhYeIwkIaztHZzdpWAApcQVCG1dVMkpVeIAfDlLTGIqHbzcQ8TkxuM0AbiA

**Comment by cristianoc** [comment] 2021-05-01 09:29
`@send.pipe` --> `@bs.send.pipe`

Note send.pipe is deprecated.

**Comment by cristianoc** [comment] 2021-05-01 09:30
The playground seems ok with `@bs.send.pipe`.

**Comment by IwanKaramazow** [comment] 2021-05-01 09:39
Thanks for the example @BlueHotDog 

[Reason snippet](https://rescript-lang.org/try?ext=re&code=C4TwDgpgBMDcBQBtAAgIwM4DoB2EDuAulBAB7AQBO2AhgDZQC21A1hAFxQCu2AlsFAF4AfDEFQARABEA8gFkACtQrpK4hCgyYV2ACaYwPSB2AF4pclTpQwSlQAlgDWgDEKAewYBlYBR7YA5mzwUFAAFOg+fv4ANFAaWNToEuRkAPQAFo604kQA+gCUgiKSHpiZTiUAxpwMENj8AsESNsoQrh7evgFq8PAAUli0bv6hTKyhhQA+Ii32We1ekQGh4ug6a+L5+QhAA)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/10634678/116778300-52ac9300-aa71-11eb-8899-ba5b47bb576b.png">

If you press the `Res` button, it will convert to [ReScript snippet](https://rescript-lang.org/try?code=C4TwDgpgBMBQACA7CB3KEAewICdEEMAbKAW3wGsIAuKAV0QEtgoBeAPhlagCIARAeQCyABXw4Azrm4IARuIB0kxABN5YBpAAUNYAEpYmbHiJQwYyQAlgJQgDEcAexIBlYDgaIA5jU3i3HzwAaKHh8cU1ubCwAegALa0JuXSgAfWT2KF4neXibLIBjWhIIRGYWWCgeMwkIeydXdy9pWAApBUIHT00ySk1kgB8OassEupd-LwjxZWmk-SA)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/10634678/116778312-6d7f0780-aa71-11eb-952b-65d5748ee452.png">

Is it possible that you did the conversion manually and made a typo? It should be `@bs.send.pipe(: t)`, not `@send.pipe(: t)`.
Which ReScript version are you using?

I added an extra test case to test that the syntax converts everything correctly here: https://github.com/rescript-lang/syntax/pull/401

**Comment by cristianoc** [comment] 2021-05-01 09:40
Also, `send.pipe` is deprecated, and will go soon.

**Comment by BlueHotDog** [comment] 2021-05-01 09:46
I did the conversion automatically. so there's definitely a bug IMO.
If you do this:
```
type t;
[@bs.new] external make: unit => t = "DOMParser";
[@bs.send.pipe: t]
external parseHtmlFromString: (string, [@bs.as "text/html"] _) => Dom.htmlDocument = "parseFromString";

Js.log(make() |> parseHtmlFromString("sdsd"));
```
you get this js code:
```
console.log(new DOMParser().parseFromString("sdsd", "text/html"));
```

which is exactly what one might expect.

But if you do this:
```
type t;
[@new] external make: unit => t = "DOMParser";
[@bs.send.pipe: t]
external parseHtmlFromString: (string, [@bs.as "text/html"] _) => Dom.htmlDocument = "parseFromString";

Js.log(make() |> parseHtmlFromString("sdsd"));
```
you get this code:
```
var Caml_external_polyfill = require("./stdlib/caml_external_polyfill.js");

console.log(Caml_external_polyfill.resolve("DOMParser")(undefined).parseFromString("sdsd", "text/html"));
```

now, i've three questions here:
- Why this magic polyfill is a thing? and where is it documented? 
- What can i do to make sure this doesnt happen in production?
- Where was some discussion i can read on on this pollyfill thingie

**Comment by IwanKaramazow** [comment] 2021-05-01 09:48
Would it be possible to send me the rescript compiler version you're using?

**Comment by BlueHotDog** [comment] 2021-05-01 10:29
I'm using this:
https://reasonml.github.io/en/try.html?rrjsx=true&reason=C4TwDgpgBMDcBQBtAAgIwM4DoB2EDuAulBAB7AQBO2AhgDZQC21A1hAFxQCu2AlsFAF4AfDEFQARABEA8gFkACtQrpK4hCgyYV2ACaYwPSB2AF4pclTpQwSlQAlgDWgDEKAewYBlYBR7YA5hwAFOg+fv4ANFAaWNToEuRkAPQAFo604kQA+gCUgiKSHphpToUAxpwMENj8AhI2yhCuHt6+AWrw8ABSWLRu-kFMrEF5AD4iDfbpzV5hAUHi6DpL4jk5sEA

**Comment by ryyppy** [comment] 2021-05-01 11:16
> @cristianoc having to manually check each file we transform would result in so much manual, careful labor since we dont even commit the JS files to git so i dont see how this is a solution - we're running rescript on thousands of files and tens of projects in a monorepo setup, doing this for evey file migration means we'll not move to rescript anytime soon which puts us between a rock and a hard place - Can't upgrade, can't trust an robust upgrade process.

I am literally in the same process for a client project of mine, and did just that (1000+ files).
Create a branch, check in the build artifacts, do the syntax transformation, rebuild the project, check the changes in the JS output.

As long as you are not upgrading the compiler + changing the syntax at the same, there shouldn't be that many considerable diffs.

**Comment by IwanKaramazow** [comment] 2021-05-01 12:01
I just checked on the latest ReScript and can't reproduce the problem, doesn't reproduce in the playground either.
This is how you do the conversion:
```
% npx rescript -v
9.1.2

% cat src/test.re
type t;
[@bs.new] external make: unit => t = "DOMParser";
[@bs.send.pipe: t]
external parseHtmlFromString: (string, [@bs.as "text/html"] _) => Dom.htmlDocument = "parseFromString";

Js.log(make() |> parseHtmlFromString("sdsd"));

% npx rescript format src/test.re
type t
@new external make: unit => t = "DOMParser"
@bs.send.pipe(: t)
external parseHtmlFromString: (string, @as("text/html") _) => Dom.htmlDocument = "parseFromString"

Js.log(make() |> parseHtmlFromString("sdsd"))

% npx rescript format src/test.re > src/test.res
% rm src/test.re

% npx rescript build
rescript: [1/3] src/test.ast

  Warning number 103
  /Users/mvalcke/Development/Praktijk/src/test.res:3:1-13

  1 │ type t
  2 │ @new external make: unit => t = "DOMParser"
  3 │ @bs.send.pipe(: t)
  4 │ external parseHtmlFromString: (string, @as("text/html") _) => Dom.htmlDo
    │ cument = "parseFromString"
  5 │

  FFI warning: This attribute is deprecated, use @send instead.

rescript: [3/3] src/test.cmj

% cat lib/js/src/test.js
// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log(new DOMParser().parseFromString("sdsd", "text/html"));

/*  Not a pure module */
```

Regarding your questions:
> Why this magic polyfill is a thing? and where is it documented?
The snippet that you showed me contained a typo in the attribute. `@send.pipe` does not exist. It should be `@bs.send.pipe` Without the `@bs.send.pipe`, the compiler tried to resolve it as a global value.

> What can i do to make sure this doesnt happen in production?
Externals can be rather unsafe. Thorough unit testing of externals can help here.

> Where was some discussion i can read on on this pollyfill thingie
This is a consequence of how externals are modelled in the ocaml compiler. Ocaml native needs to deal with the c runtime, ReScript needs to support a js runtime across browsers/node.

Will close this issue, the conversion works ok in the playground and latest rescript on npm.

**Closed by IwanKaramazow** 2021-05-01 12:01 UTC
