### ISSUE TITLE
“typecore.ml” error when trying to use a default value with an unlabeled argument

### ISSUE THREAD

**Issue by johnridesabike** [rescript-lang/syntax#216] opened 2020-12-30 00:15 UTC
```res
let f = (x, y=2, z) => x + y + z
```
Output:
```
Unexpected Error
File "typecore.ml", line 2758, characters 6-12: Assertion failed
```

I assume this is an issue with the ReScript syntax because the same error doesn’t occur with Reason syntax.

**Comment by IwanKaramazow** [comment] 2020-12-30 06:32
Thanks for the report!

The root cause is that the there's a syntax error not being reported. I will submit a fix.
```
let f =( x, y=2, z) => x + y + z
           ^^^ missing `~`, did you mean `~y`?
```

**Comment by IwanKaramazow** [comment] 2020-12-30 09:04
Fixed in master!

**Closed** 2020-12-30 09:04 UTC
